services:
  postgres:
    image: ${DB_IMAGE}
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
