services:
  teampass-web:
    image: dormancygrace/teampass
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 80
    volumes:
      - teampass-html:/var/www/html
volumes:
  teampass-html:
  teampass-db:
