services:
  psono-server:
    image: psono/psono-server:latest
    container_name: psono-server
    ports:
      - "10100:80" # Cambia el puerto externo si lo necesitas
    environment:
      - DEBUG=False # Cambiar a True para depuración
      - SECRET_KEY=iqueingufo3LohshoohoG3tha2zou6 # Genera una clave secreta
      - ALLOWED_HOSTS=localhost # Dominio o IP del servidor
      - EMAIL_FROM=Vaultwarden
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=fernandotzoc01@gmail.com
      - EMAIL_PASSWORD=tkghgbbtequlyptk
      - DATABASE_HOST=psono-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=psono
      - DATABASE_USER=psono_user
      - DATABASE_PASSWORD=psono_password
    depends_on:
      - psono-db
    volumes:
      - psono-data:/data

  psono-db:
    image: postgres:13
    container_name: psono-db
    environment:
      POSTGRES_USER: psono_user
      POSTGRES_PASSWORD: psono_password
      POSTGRES_DB: psono
    volumes:
      - psono-db-data:/var/lib/postgresql/data

volumes:
  psono-data:
  psono-db-data:
