version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlServerDocker
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=6F@ANy#5nowY4p
      - MSSQL_PID=Express
    ports:
      - 1212:1433
    volumes:
      - dbdata:/var/opt/mssql
volumes:
  dbdata:
