version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysqlDocker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: 'caching_sha2_password'
      TZ: 'Etc/GMT+6'
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - mysql_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

networks:
  mysql_network:

volumes:
  dbdata:
