services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlServerDocker
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - mssqldbdata:/var/opt/mssql
    networks:
      - mssql_network

networks:
  mssql_network:


volumes:
  mssqldbdata:
